import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';

const API = location.hostname === 'localhost' && location.port !== '4000'
  ? 'http://localhost:4000'
  : '';
const publicFirebaseConfig = {
  apiKey: 'AIzaSyBo7ZmtXQrLFKFBBinkYLKDlccapZQz1Ss',
  authDomain: 'skillcircle-87a66.firebaseapp.com',
  projectId: 'skillcircle-87a66',
  storageBucket: 'skillcircle-87a66.firebasestorage.app',
  messagingSenderId: '602538232951',
  appId: '1:602538232951:web:26de068e28f0251ddf8a72'
};
const root = document.querySelector('#app');
let auth, user, profile, posts = [], students = [], notices = [], tab = 'home', theme = localStorage.getItem('skillcircle-theme') || 'light';
document.documentElement.dataset.theme = theme;

const esc = (value='') => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function api(path, options={}) { const token = user && await user.getIdToken(); const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...(options.headers || {}) } }); if (!response.ok) throw new Error((await response.json().catch(()=>null))?.error || 'Request failed'); return response.status === 204 ? null : response.json(); }
async function start() { try { const serverConfig = await fetch(`${API}/config`).then(response => response.json()); const config = { ...publicFirebaseConfig, ...Object.fromEntries(Object.entries(serverConfig).filter(([, value]) => value)) }; auth = getAuth(initializeApp(config)); onAuthStateChanged(auth, next => { user = next; next ? load() : renderLogin(); }); } catch (error) { renderLogin(`Firebase could not start: ${error.message}`); } }
async function load() { try { [profile, posts, notices] = await Promise.all([api('/api/me'), api('/api/posts'), api('/api/notifications')]); if (tab === 'discover') students = await api('/api/users'); renderApp(); } catch (error) { renderApp(error.message); } }
function renderLogin(message='') { root.innerHTML = `<main class="auth"><span class="mark">S</span><p class="eyebrow">Your student network</p><h1>Make your next connection count.</h1><p>Find peers, share your work, and build a circle around what you are learning.</p><form id="login" class="form" style="max-width:28rem;width:100%"><input name="email" type="email" placeholder="Email address" required><input name="password" type="password" placeholder="Password" minlength="6" required><button class="primary" type="submit">Log in</button><button class="secondary" type="button" id="google">Continue with Google</button><button class="secondary" type="button" id="create">Create account</button><p class="muted">${esc(message)}</p></form></main>`; document.querySelector('#login').onsubmit = async event => { event.preventDefault(); const data = new FormData(event.currentTarget); if (!auth) { event.currentTarget.querySelector('.muted').textContent = 'Firebase is still loading. Refresh and try again.'; return; } try { await signInWithEmailAndPassword(auth, data.get('email'), data.get('password')); } catch(error) { event.currentTarget.querySelector('.muted').textContent = error.message; } }; document.querySelector('#google').onclick = () => auth ? signInWithPopup(auth, new GoogleAuthProvider()) : renderLogin('Firebase is still loading. Refresh and try again.'); document.querySelector('#create').onclick = async () => { const form = document.querySelector('#login'); const data = new FormData(form); if (!auth) { form.querySelector('.muted').textContent = 'Firebase is still loading. Refresh and try again.'; return; } try { await createUserWithEmailAndPassword(auth, data.get('email'), data.get('password')); } catch(error) { form.querySelector('.muted').textContent = error.message; } }; }
function renderApp(message='') { const name = profile?.name || user.displayName || user.email.split('@')[0]; const initials = name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase(); const nav = [['home','⌂','Home'],['discover','◎','Discover'],['notifications','◌','Activity'],['profile','◯','Profile']]; root.innerHTML = `<div class="shell"><header class="topbar"><a class="brand" href="#"><span class="mark">S</span>SkillCircle</a><div class="top-actions"><button class="icon" id="theme">${theme==='light'?'☾':'☀'}</button><button class="avatar" data-tab="profile">${initials}</button></div></header><main class="workspace"><aside class="welcome"><p class="eyebrow">Good to see you</p><h1>${esc(name.split(' ')[0])}<br><em>keep building.</em></h1><p class="muted">Your circle grows one thoughtful connection at a time.</p><div class="mini"><span class="avatar">${initials}</span><div><strong>${esc(name)}</strong><span>${esc(profile?.college || 'Add your college')}</span></div></div></aside><section><div id="message" class="notice" ${message?'':'hidden'}>${esc(message)}</div>${view()}</section></main><nav class="bottom">${nav.slice(0,2).map(item=>navButton(item)).join('')}<button class="create" id="new-post">+</button>${nav.slice(2).map(item=>navButton(item)).join('')}</nav><div id="modal"></div></div>`; bind(); }
function navButton([id, icon, label]) { return `<button class="${tab===id?'active':''}" data-tab="${id}"><span>${icon}</span>${label}</button>`; }
function view() { if(tab==='discover') return `<div class="heading"><div><p class="eyebrow">Find your people</p><h2>Discover students</h2></div></div><input id="search" class="search" placeholder="Search by name, college, or skill"><div class="grid">${students.length ? students.map(student => `<article class="card student"><span class="avatar">${esc(student.name?.slice(0,2).toUpperCase())}</span><h3>${esc(student.name)}</h3><p>${esc(student.college || 'Student')}</p><div class="tags">${(student.skills||[]).slice(0,3).map(skill=>`<span>${esc(skill)}</span>`).join('')}</div><button class="secondary full" data-connect="${esc(student.email)}">Connect</button></article>`).join('') : '<div class="empty"><h3>No students found</h3><p class="muted">Try searching for a name or skill.</p></div>'}</div>`; if(tab==='notifications') return `<div class="heading"><div><p class="eyebrow">Stay in the loop</p><h2>Activity</h2></div></div><div class="list">${notices.length ? notices.map(notice=>`<article class="card"><strong>${esc(notice.message)}</strong><p class="muted">${new Date(notice.createdAt).toLocaleDateString()}</p></article>`).join('') : '<div class="empty"><h3>All quiet here</h3><p class="muted">Likes, comments, and connection updates will show up here.</p></div>'}</div>`; if(tab==='profile') return `<div class="heading"><div><p class="eyebrow">Your professional snapshot</p><h2>Profile</h2></div><button class="secondary" id="logout">Sign out</button></div><form id="profile" class="form card"><label>Bio<textarea name="bio" placeholder="A short introduction">${esc(profile?.bio)}</textarea></label><button class="secondary" type="button" id="ai">Suggest bio with AI</button><label>College<input name="college" value="${esc(profile?.college)}" placeholder="College or university"></label><label>Skills<input name="skills" value="${esc((profile?.skills||[]).join(', '))}" placeholder="React, research, design"></label><button class="primary">Save profile</button></form>`; return `<div class="heading"><div><p class="eyebrow">Your circle</p><h2>Home feed</h2></div><button class="secondary" id="new-post-alt">Share an update</button></div><div class="feed">${posts.length ? posts.map(post=>`<article class="card"><div class="author"><span class="avatar">${esc(post.author?.name?.slice(0,2).toUpperCase())}</span><div><strong>${esc(post.author?.name || 'Student')}</strong><small>${new Date(post.createdAt).toLocaleDateString()}</small></div></div><p class="post-text">${esc(post.text)}</p>${post.imageUrl?`<img class="post-image" src="${esc(post.imageUrl)}" alt="Post attachment">`:''}<div class="actions"><button data-like="${post._id}">♡ ${post.likes?.length||0}</button><button data-comment="${post._id}">◌ ${post.comments?.length||0} comments</button></div></article>`).join('') : '<div class="empty"><h3>Your feed is ready for you</h3><p class="muted">Share an update or discover students to start your circle.</p></div>'}</div>`; }
function bind() { document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=async()=>{ tab=button.dataset.tab; if(tab==='discover') students=await api('/api/users'); renderApp(); }); document.querySelector('#theme').onclick=()=>{ theme=theme==='light'?'dark':'light'; localStorage.setItem('skillcircle-theme',theme); document.documentElement.dataset.theme=theme; renderApp(); }; document.querySelector('#new-post')?.addEventListener('click', composer); document.querySelector('#new-post-alt')?.addEventListener('click',composer); document.querySelector('#logout')?.addEventListener('click',()=>signOut(auth)); document.querySelectorAll('[data-like]').forEach(button=>button.onclick=async()=>{await api(`/api/posts/${button.dataset.like}/like`,{method:'POST'});await load()}); document.querySelectorAll('[data-comment]').forEach(button=>button.onclick=async()=>{const text=prompt('Add a comment');if(text) {await api(`/api/posts/${button.dataset.comment}/comments`,{method:'POST',body:JSON.stringify({text})});await load()}}); document.querySelectorAll('[data-connect]').forEach(button=>button.onclick=async()=>{await api('/api/connections',{method:'POST',body:JSON.stringify({email:button.dataset.connect})}); show('Connection request sent.')}); document.querySelector('#profile')?.addEventListener('submit',saveProfile); document.querySelector('#ai')?.addEventListener('click',suggestBio); document.querySelector('#search')?.addEventListener('input',async event=>{students=await api(`/api/users?search=${encodeURIComponent(event.target.value)}`);renderApp()}); }
function show(message) { const element=document.querySelector('#message'); element.hidden=false;element.textContent=message; }
function composer() { document.querySelector('#modal').innerHTML='<div class="modal"><form id="composer" class="composer"><div class="heading"><h2>Create post</h2><button type="button" class="icon" id="close">×</button></div><textarea name="text" placeholder="What are you learning, making, or thinking about?" required></textarea><input name="image" type="file" accept="image/*"><p id="composer-error" class="muted" hidden></p><button class="primary">Publish post</button></form></div>'; document.querySelector('#close').onclick=()=>document.querySelector('#modal').innerHTML=''; document.querySelector('#composer').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;const button=form.querySelector('button.primary');const error=document.querySelector('#composer-error');button.disabled=true;button.textContent='Publishing...';error.hidden=true;try{const data=new FormData(form);let imageUrl;const file=data.get('image');if(file?.size){const reader=new FileReader();const imageData=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read the image.'));reader.readAsDataURL(file)});imageUrl=(await api('/api/uploads',{method:'POST',body:JSON.stringify({data:imageData})})).url}await api('/api/posts',{method:'POST',body:JSON.stringify({text:data.get('text'),imageUrl})});document.querySelector('#modal').innerHTML='';await load()}catch(publishError){error.textContent=publishError.message;error.hidden=false;button.disabled=false;button.textContent='Publish post'}}; }
async function saveProfile(event) { event.preventDefault(); const data=new FormData(event.currentTarget); await api('/api/me',{method:'PUT',body:JSON.stringify({bio:data.get('bio'),college:data.get('college'),skills:String(data.get('skills')).split(',').map(value=>value.trim()).filter(Boolean)})}); await load(); }
async function suggestBio() { const form=new FormData(document.querySelector('#profile')); const result=await api('/api/ai/bio',{method:'POST',body:JSON.stringify({college:form.get('college'),skills:form.get('skills')})}); document.querySelector('[name=bio]').value=result.bio; }
start();
